apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: default
  labels:
    app: homepage
spec:
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:v0.9.13 # {"$imagepolicy": "flux-system:homepage"}
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: config-homepage
              mountPath: /app/config
            - name: icons-homepage
              mountPath: /app/public/icons
      volumes:
        - name: config-homepage
          hostPath:
            path: /mnt/raid/nas/homepage
        - name: icons-homepage
          hostPath:
            path: /mnt/raid/nas/homepage/icon
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: default
  labels:
    service: homepage
spec:
  selector:
    app: homepage
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`homepage.lan`)
      services:
        - kind: Service
          name: homepage
          port: 3000
  tls:
    secretName: homepage-secret
