apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng
  namespace: default
  labels:
    app: searxng
spec:
  selector:
    matchLabels:
      app: searxng
  template:
    metadata:
      labels:
        app: searxng
    spec:
      containers:
        - name: searxng
          image: docker.io/searxng/searxng:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: searxng
  namespace: default
  labels:
    service: searxng
spec:
  selector:
    app: searxng
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: searxng
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`searxng.lan`)
    services:
      - kind: Service
        name: searxng
        port: 8080
  tls:
    secretName: searxng-secret
