apiVersion: apps/v1
kind: Deployment
metadata:
  name: trilium
  namespace: default
  labels:
    app: trilium
spec:
  selector:
    matchLabels:
      app: trilium
  template:
    metadata:
      labels:
        app: trilium
    spec:
      containers:
      - name: trilium
        image: docker.io/triliumnext/notes:latest
        env:
        - name: TRILIUM_DATA_DIR
          value: "/home/node/trilium-data"
        - name: TRILIUM_PORT
          value: "8080"
        volumeMounts:
          - name: data
            mountPath: /home/node/trilium-data
      volumes:
        - name: data
          hostPath:
            path: /mnt/raid/nas/note/data
---
apiVersion: v1
kind: Service
metadata:
  name: trilium
  namespace: default
  labels:
    service: trilium
spec:
  selector:
    app: trilium
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: trilium
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`note.lan`)
      services:
        - kind: Service
          name: trilium
          port: 8080
  tls:
    secretName: note-secret
