---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: paperless
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: paperless
  policy:
    semver:
      range: '>=1.0.0'
