{
 "title": "Telegraf & Influx Windows Host Overview",
 "description": "Windows host dashboard for telegraf metrics pumped into influxdb",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "SHOW TAG VALUES FROM \"win_system\" WITH KEY = \"host\""
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": "SHOW TAG VALUES FROM \"win_disk\" WITH KEY = \"instance\" WHERE host =~ /$hostname/"
   },
   {
    "name": "process",
    "label": "Process",
    "query": "SHOW TAG VALUES FROM \"win_proc\" WITH KEY = \"instance\" WHERE host =~ /$hostname/"
   },
   {
    "name": "network",
    "label": "Network Interface",
    "query": "SHOW TAG VALUES FROM \"win_net\" WITH KEY = \"instance\" WHERE host =~ /$hostname/"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temp Motherboard",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sensor",
     "query": "SELECT mean(\"Value\") as PCH FROM \"Sensor\" WHERE (\"Name\"::tag = 'PCH') AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Name::tag", "operator": "=", "value": "PCH" }
     ]
    },
    {
     "alias": "$tag_host: $col",
     "query": "SELECT mean(\"Value\") as CPU FROM \"Sensor\" WHERE (\"Name\"::tag = 'CPU') AND host =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc"
    },
    {
     "alias": "$tag_host: $col",
     "query": "SELECT mean(\"Value\") as System FROM \"Sensor\" WHERE (\"Name\"::tag = 'System') AND host =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc"
    },
    {
     "alias": "$tag_host: $col",
     "query": "SELECT mean(\"Value\") as \"VRM MOS\" FROM \"Sensor\" WHERE (\"Name\"::tag = 'VRM MOS') AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc"
    },
    {
     "alias": "$tag_host: $col",
     "query": "SELECT mean(\"Value\") as PCIe FROM \"Sensor\" WHERE (\"Name\"::tag = 'PCIe x1') AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc"
    },
    {
     "alias": "$tag_host: $col",
     "query": "SELECT mean(\"Value\") as \"CPU Socket\" FROM \"Sensor\" WHERE (\"Name\"::tag = 'CPU Socket') AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc"
    },
    {
     "alias": "$tag_host: $col",
     "query": "SELECT mean(\"Value\") as M2 FROM \"Sensor\" WHERE (\"Name\"::tag = 'M2_1') AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc"
    }
   ]
  },
  {
   "title": "GPU Temp",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sensor",
     "query": "SELECT mean(\"Value\") as \"GPU Hot Spot\" FROM \"Sensor\" WHERE  (\"Name\"::tag = 'GPU Hot Spot') AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Name::tag", "operator": "=", "value": "GPU Core" },
      { "condition": "AND", "key": "Name::tag", "operator": "=", "value": "GPU Hot Spot" }
     ]
    },
    {
     "alias": "$tag_host: $col",
     "query": "SELECT mean(\"Value\") as \"GPU Core\" FROM \"Sensor\" WHERE (\"Name\"::tag = 'GPU Core' ) AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc"
    }
   ]
  },
  {
   "title": "Temp Core",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "query": "SELECT mean(\"Value\") as \"Temp Core Max\" FROM \"Sensor\" WHERE (\"Name\"::tag = 'Core Max') AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"Available_Bytes\") as \"Available Bytes\", mean(\"Pool_Nonpaged_Bytes\") as \"Pool Nonpaged Bytes\", mean(\"Pool_Paged_Bytes\") as \"Pool Paged Bytes\" FROM \"win_mem\" WHERE host =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$hostname: $col",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT mean(\"Percent_Privileged_Time\") AS \"% Priviledged Time\", mean(\"Percent_User_Time\") AS \"% User Time\", mean(\"Percent_Interrupt_Time\") AS \"% Interrupt Time\", mean(\"Percent_Processor_Time\") AS \"% Processor Time\" FROM \"win_cpu\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "Percent_Privileged_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Priviledged Time" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_User_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% User Time" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_Interrupt_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Interrupt Time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "GPU Package power",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "query": "SELECT mean(\"Value\") as \"GPU Package\" FROM \"Sensor\" WHERE (\"Name\"::tag = 'GPU Package') AND host =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc"
    }
   ]
  },
  {
   "title": "CPU package power",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sensor",
     "query": "SELECT mean(\"Value\") as \"CPU package power\" FROM \"Sensor\" WHERE (\"Name\"::tag = 'CPU Package') AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Name::tag", "operator": "=", "value": "CPU Package" }
     ]
    }
   ]
  },
  {
   "title": "Ressources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$hostname: $col",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT mean(\"Percent_Privileged_Time\") AS \"% Priviledged Time\", mean(\"Percent_User_Time\") AS \"% User Time\", mean(\"Percent_Interrupt_Time\") AS \"% Interrupt Time\", mean(\"Percent_Processor_Time\") AS \"% Processor Time\" FROM \"win_cpu\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "Percent_Privileged_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Priviledged Time" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_User_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% User Time" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_Interrupt_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Interrupt Time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Utilisation GPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sensor",
     "query": "SELECT mean(\"Value\") as \"Mémoire GPU dédié\" FROM \"Sensor\" WHERE (\"Name\"::tag = 'D3D Dedicated Memory Used') AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Name::tag", "operator": "=", "value": "D3D Dedicated Memory Used" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"Available_Bytes\") as \"Available Bytes\", mean(\"Pool_Nonpaged_Bytes\") as \"Pool Nonpaged Bytes\", mean(\"Pool_Paged_Bytes\") as \"Pool Paged Bytes\" FROM \"win_mem\" WHERE host =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host: $col",
     "query": "SELECT mean(total) as total FROM \"mem\" WHERE host =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc"
    }
   ]
  },
  { "title": "Temp", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Temp Core Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "query": "SELECT mean(\"Value\") as \"Temp Core Max\" FROM \"Sensor\" WHERE (\"Name\"::tag = 'Core Max') AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc"
    }
   ]
  },
  {
   "title": "GPU Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sensor",
     "query": "SELECT mean(\"Value\") as \"GPU Hot Spot\" FROM \"Sensor\" WHERE  (\"Name\"::tag = 'GPU Hot Spot') AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Name::tag", "operator": "=", "value": "GPU Core" },
      { "condition": "AND", "key": "Name::tag", "operator": "=", "value": "GPU Hot Spot" }
     ]
    },
    {
     "alias": "$tag_host: $col",
     "query": "SELECT mean(\"Value\") as \"GPU Core\" FROM \"Sensor\" WHERE (\"Name\"::tag = 'GPU Core' ) AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc"
    }
   ]
  },
  {
   "title": "Temp Motherboard",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sensor",
     "query": "SELECT mean(\"Value\") as PCH FROM \"Sensor\" WHERE (\"Name\"::tag = 'PCH') AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Name::tag", "operator": "=", "value": "PCH" }
     ]
    },
    {
     "alias": "$tag_host: $col",
     "query": "SELECT mean(\"Value\") as CPU FROM \"Sensor\" WHERE (\"Name\"::tag = 'CPU') AND host =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc"
    },
    {
     "alias": "$tag_host: $col",
     "query": "SELECT mean(\"Value\") as System FROM \"Sensor\" WHERE (\"Name\"::tag = 'System') AND host =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc"
    },
    {
     "alias": "$tag_host: $col",
     "query": "SELECT mean(\"Value\") as \"VRM MOS\" FROM \"Sensor\" WHERE (\"Name\"::tag = 'VRM MOS') AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc"
    },
    {
     "alias": "$tag_host: $col",
     "query": "SELECT mean(\"Value\") as PCIe FROM \"Sensor\" WHERE (\"Name\"::tag = 'PCIe x1') AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc"
    },
    {
     "alias": "$tag_host: $col",
     "query": "SELECT mean(\"Value\") as \"CPU Socket\" FROM \"Sensor\" WHERE (\"Name\"::tag = 'CPU Socket') AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc"
    },
    {
     "alias": "$tag_host: $col",
     "query": "SELECT mean(\"Value\") as M2 FROM \"Sensor\" WHERE (\"Name\"::tag = 'M2_1') AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc"
    }
   ]
  },
  {
   "title": "Alimentation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU package power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Sensor",
     "query": "SELECT mean(\"Value\") as \"CPU package power\" FROM \"Sensor\" WHERE (\"Name\"::tag = 'CPU Package') AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Name::tag", "operator": "=", "value": "CPU Package" }
     ]
    }
   ]
  },
  {
   "title": "GPU Package",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "query": "SELECT mean(\"Value\") as \"GPU Package\" FROM \"Sensor\" WHERE (\"Name\"::tag = 'GPU Package') AND host =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc"
    }
   ]
  }
 ]
}