apiVersion: apps/v1
kind: Deployment
metadata:
  name: owncloud
  namespace: default
  labels:
    app: owncloud
spec:
  selector:
    matchLabels:
      app: owncloud
  template:
    metadata:
      labels:
        app: owncloud
    spec:
      hostAliases:
      - ip: "192.168.1.200"
        hostnames:
          - "owncloud.lan"
          - "keycloak.lan"
      containers:
        - name: owncloud
          image: docker.io/owncloud/ocis-rolling:latest
          ports:
            - containerPort: 9200
            - containerPort: 9233
          command: ["/bin/sh","-c","ocis init || true; ocis server"]
          env:
            - name: OCIS_INSECURE
              value: "true"
            - name: PROXY_TLS
              value: "false"
            - name: OCIS_URL
              value: "https://owncloud.lan"
            - name: PROXY_CSP_CONFIG_FILE_LOCATION
              value: "/etc/ocis/csp.yaml"
            - name: COLLABORA_DOMAIN
              value: "office.lan"
            - name: NATS_NATS_HOST
              value: "0.0.0.0"
            - name: GATEWAY_GRPC_ADDR
              value: "0.0.0.0:9142"
            - name: FRONTEND_APP_HANDLER_SECURE_VIEW_APP_ADDR
              value: "com.owncloud.api.collaboration.CollaboraOnline"
            - name: GRAPH_AVAILABLE_ROLES
              value: "b1e2218d-eef8-4d4c-b82d-0f1a1b48f3b5,a8d5fe5e-96e3-418d-825b-534dbdf22b99,fb6c3e19-e378-47e5-b277-9732f9de6e21,58c63c02-1d89-4572-916a-870abc5a1b7d,2d00ce52-1fc2-4dbc-8b95-a73b73395f5a,1c996275-f1c9-4e71-abdf-a42f6495e960,312c0871-5ef7-4b3a-85b6-0e4074c64049,aa97fe03-7980-45ac-9e50-b325749fd7e6"
            - name: MICRO_REGISTRY_ADDRESS
              value: "127.0.0.1:9233"
            - name: NATS_NATS_PORT
              value: "9233"
            - name: OCIS_OIDC_ISSUER
              value: "https://keycloak.lan/realms/lan"
            - name: OCIS_OIDC_CLIENT_ID
              value: "ocis"
            - name: PROXY_OIDC_REWRITE_WELLKNOWN
              value: "true"
          volumeMounts:
            - name: config
              mountPath: /etc/ocis
            - name: data
              mountPath: /var/lib/ocis
      volumes:
        - name: config
          hostPath:
            path: /mnt/raid/nas/ocis/ocis-config
        - name: data
          hostPath:
            path: /mnt/raid/nas/ocis/ocis-data
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: owncloud
  labels:
    service: owncloud
spec:
  selector:
    app: owncloud
  ports:
    - port: 9200
      targetPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: registry
  labels:
    service: registry
spec:
  selector:
    app: owncloud
  ports:
    - port: 9233
      targetPort: 9233
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: default
  name: owncloud
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`owncloud.lan`)
      services:
        - kind: Service
          name: owncloud
          port: 9200
  tls:
    secretName: owncloud-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collaboration
  namespace: default
  labels:
    app: collaboration
spec:
  selector:
    matchLabels:
      app: collaboration
  template:
    metadata:
      labels:
        app: collaboration
    spec:
      hostAliases:
      - ip: "192.168.1.200"
        hostnames:
          - "owncloud.lan"
          - "office.lan"
      containers:
        - name: collaboration
          image: docker.io/owncloud/ocis-rolling:latest
          ports:
            - containerPort: 9300
          command: ["/bin/sh","-c","ocis collaboration server"]
          env:
            - name: COLLABORATION_GRPC_ADDR
              value: "0.0.0.0:9301"
            - name: COLLABORATION_HTTP_ADDR
              value: "0.0.0.0:9300"
            - name: COLLABORATION_WOPI_SRC
              value: "https://wopi.lan"
            - name: COLLABORATION_APP_ADDR
              value: "https://office.lan"
            - name: COLLABORATION_APP_ICON
              value: "https://office.lan/favicon.ico"
            - name: COLLABORATION_APP_NAME
              value: "CollaboraOnline"
            - name: COLLABORATION_APP_PRODUCT
              value: "Collabora"
            - name: COLLABORATION_APP_INSECURE
              value: "true"
            - name: COLLABORATION_CS3API_DATAGATEWAY_INSECURE
              value: "true"
            - name: MICRO_REGISTRY
              value: "nats-js-kv"
            - name: MICRO_REGISTRY_ADDRESS
              value: "registry:9233"
            - name: OCIS_URL
              value: "https://owncloud.lan"
          volumeMounts:
            - name: config
              mountPath: /etc/ocis
      volumes:
        - name: config
          hostPath:
            path: /mnt/raid/nas/ocis/ocis-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: wopi
  labels:
    service: wopi
spec:
  selector:
    app: collaboration
  ports:
    - port: 9300
      targetPort: 9300
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: default
  name: wopi
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`wopi.lan`)
      services:
        - kind: Service
          name: wopi
          port: 9300
  tls:
    secretName: wopi-secret