---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: calibre
  namespace: flux-system
spec:
  image: docker.io/crocodilestick/calibre-web-automated
  interval: 1h0m0s
