kind: Deployment
apiVersion: apps/v1
metadata:
  name: headlamp
  namespace: default
spec:
  selector:
    matchLabels:
      k8s-app: headlamp
  template:
    metadata:
      labels:
        k8s-app: headlamp
    spec:
      containers:
      - name: headlamp
        image: ghcr.io/headlamp-k8s/headlamp:v0.30.0
        args:
        - "-in-cluster"
        - "-plugins-dir=/headlamp/plugins"
        ports:
        - containerPort: 4466
---
kind: Secret
apiVersion: v1
metadata:
  name: headlamp-admin
  namespace: default
  annotations:
    kubernetes.io/service-account.name: "admin"
type: kubernetes.io/service-account-token
---
kind: Service
apiVersion: v1
metadata:
  name: headlamp
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 4466
  selector:
    k8s-app: headlamp
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headlamp
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`homepage.lan`)
      services:
        - kind: Service
          name: headlamp
          port: 80
  tls:
    secretName: homepage-secret
