---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: headlamp
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: headlamp
  policy:
    semver:
      range: '>=0.0.0'